### ISSUE TITLE
[SUGGESTION] Display Cards in High Res when Hovering

### ISSUE THREAD

**Issue by BBeretta** [BAA-Studios/MOOgiwara#53]
**Is your feature request related to a problem? Please describe.**
I'm following and studying your framework, they are excellent. Keep it up!
(I'm studying Phaser to try to contribute).

For now, I'd like to share an improvement to the **displayCardInHigherRes** method.
I believe that the "**Click**" function to display and remove the display requires muscular effort.

**Describe the solution you'd like**
My suggestion is to use **PointerOver** when hovering the mouse over the Card and displaying it in real time and when leaving the **PointerOver** the card, the card will automatically remove. Very common in current TCG styles.

Here is a suggestion for improvements to better understand.
![displayCardInHigherRes - Enhancement](https://user-images.githubusercontent.com/7991639/217031407-267ae216-2874-4d2b-9704-ccd503f414b2.png)

Let me know if you need more details!
Thank you!!

**Comment by Bratah123** [comment]
This is an idea we have in mind.
A lot of our interactions are inspired from Hearthstone and Legends of Runeterra (LoR)

We are looking to implement a hoverOverDisplay similar to: 

![image](https://user-images.githubusercontent.com/58405975/217078390-4bd67f76-bf91-4292-8c64-1bce80781f2c.png)
Rather than giving up screen real estate like displayed in your demo screenshot

We will not be removing the right click to display as it allows players to admire artwork, and maybe get a better look at the card!

![image](https://user-images.githubusercontent.com/58405975/217078713-637b18fb-0150-4956-a65e-ed4812bcf19f.png)

Example of when right clicking ^

Also thanks for your continue support! Even creating an issue post is a contribution for this project, this will be a good first suggestion from someone outside of this project. :)

**Comment by BBeretta** [comment]
Great!! I liked the idea!! 
Suggestions:
 - Who knows, having an option where the user can choose between PointerOver/PointerOut and PointerDown (the clicks)
 
 - The User has the freedom to resize the high resolution card and also free for the user to position it wherever wants. (Can move in the corner, or in the middle, in the middle of the right or left side, etc...) It would be cool! [When placing the card, fix the position the user wanted] 
Both would be low priority. 

Thank you!

**Comment by Bratah123** [comment]
> **Is your feature request related to a problem? Please describe.** I'm following and studying your framework, they are excellent. Keep it up! (I'm studying Phaser to try to contribute).
> 
> For now, I'd like to share an improvement to the **displayCardInHigherRes** method. I believe that the "**Click**" function to display and remove the display requires muscular effort.
> 
> **Describe the solution you'd like** My suggestion is to use **PointerOver** when hovering the mouse over the Card and displaying it in real time and when leaving the **PointerOver** the card, the card will automatically remove. Very common in current TCG styles.
> 
> Here is a suggestion for improvements to better understand. ![displayCardInHigherRes - Enhancement](https://user-images.githubusercontent.com/7991639/217031407-267ae216-2874-4d2b-9704-ccd503f414b2.png)
> 
> Let me know if you need more details! Thank you!!

Completed this feature as to modern TCGs in commit: 62ae7ed3b5b0191456104f232602f5ef53b48b12
When you hover over a card for long enough, it will display a slightly higher res card.

See Demo Below:

https://user-images.githubusercontent.com/58405975/230799292-b1cc8f98-aeaf-4167-b8b8-1f532c26e8e5.mp4
