### ISSUE TITLE
[BUG] NPM run failed

### ISSUE THREAD

**Issue by andreaadinolfi** [BAA-Studios/MOOgiwara#76]
Hi!
I tried to run the application following the instructions in the README, but I encountered the following issue:
Maybe I'm doing something wrong with TypeScript.
Thanks in advance.

![Screenshot 2024-06-30 alle 23 32 59](https://github.com/BAA-Studios/MOOgiwara/assets/24621106/5465e1f7-78a1-4e16-a441-4e0a1572fe57)

**Comment by BBeretta** [comment]
Hello my friend!

You can use an alternative instead of using nodemon, and it works:

[Steps]
1) cd server
2) Install tsx (npm install tsx)
3) Go to the package.json, on line 12 ("start": "nodemon src/index.ts"), replace nodemon with tsx (it will be like this: "start": "tsx src/index.ts")

Done! This will run the server, and you can execute the client.

**Comment by andreaadinolfi** [comment]
Thank you!
It worked!

**Comment by andreaadinolfi** [comment]
How can i contribute to the project?
I'd like to learn typescript and have a OPTCG sim that runs on my broweser, maybe on my phone.
Do you know if the project is still alive or was it abandoned?
Thanks.

**Comment by andreaadinolfi** [comment]
Hi my friend,
would you like to continue development together?

**Comment by andreaadinolfi** [comment]
I’m currently working on counter step.

￼￼
